### ISSUE TITLE
Cannot read property 'count' of null

### ISSUE THREAD

**Issue by dciccale** [chevex-archived/mongoose-auto-increment#63]
In development I am seeding my database every time the server starts. So before seeding the db, I clear all my collections doing `mongoose.model('SomeModel').remove()` but when I do this for the model `'IdentityCounter'` which is the one this plugin creates for me, it gives an error when it tries to increment.

any other way to clear/reset this collection completely without breaking it?

thanks in advance

**Comment by jiangzihao** [comment]
I have the same problem with you.

I was trying to test my code with mocha.

There is the Err stack
```
Uncaught TypeError: Cannot read property 'count' of null
      at node_modules/mongoose-auto-increment/index.js:160:61
      at model.Query.<anonymous> (node_modules/mongoose/lib/model.js:3411:16)
      at node_modules/kareem/index.js:127:16
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by tomasztomys** [comment]
the same problem here

**Comment by bertop89** [comment]
+1

**Comment by olegelantsev** [comment]
I had similar stacktrace when inserted item in collection.
Further investigation showed that I used custom identifier field instead of default `_id` like:
```
exampleSchema.plugin(autoIncrement.plugin, { model: 'Example', field: 'customId' });
```

Explicitly declaring such field in schema solved the problem for me, i.e.
```
var exampleSchema = new Schema({
    customId: Number,
    // ...
});
```

**Comment by ozero1st** [comment]
me too ... Uncaught TypeError: Cannot read property 'count' of null

**Comment by wandolch** [comment]
+1

**Comment by bandreetto** [comment]
+1

**Comment by blueyestar** [comment]
+1

**Comment by imohitagrwal** [comment]
+1
