### ISSUE TITLE
MongoError: The field 'required' is not valid for an index specification

### ISSUE THREAD

**Issue by Siddeshgad** [chevex-archived/mongoose-auto-increment#74]
Unhandled rejection MongoError: The field 'required' is not valid for an index specification. Specification: { ns: "xyz.identitycounters", key: { field: 1, model: 1 }, name: "field_1_model_1", unique: true, required: true, index: -1, background: true }
    at Function.MongoError.create (.../node_modules/mongodb-core/lib/error.js:31:11)
    at .../node_modules/mongodb/lib/db.js:1093:80
    at .../node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

This statement was executed
**identitycounters.createIndex({ field: 1, model: 1 }, { unique: true, required: true, index: -1, background: true })**

https://docs.mongodb.com/manual/reference/method/db.collection.createIndex/
As per the definitions listed above, it does not contain required property. 

I have already sent a PR for the above changes
https://github.com/chevex-archived/mongoose-auto-increment/pull/73

Thank you.

**Comment by highfeed** [comment]
Hi. Fix it, please.

**Comment by yuk320** [comment]
index has the same problem

**Comment by highfeed** [comment]
Just use mongoose-sequelize.

**Comment by pulselife** [comment]
How to fix this bug?

**Comment by XBeg9** [comment]
+1

**Comment by HansITChange** [comment]
Any updates on this ? Still not working...

**Comment by stephengardner** [comment]
Hey the fix here has been PRd, what's going on here?  This needs a merge

**Comment by germanurrus** [comment]
I'm having the same issue, running the app over Docker...over Ubuntu in a real machine does not show the error, it only happens on a docker container. Please fix it. Thanks

**Comment by trueter** [comment]
+1!

**Comment by pandashuai** [comment]
+1

**Comment by VunterSlaush** [comment]
+1

**Comment by raphaelsoul** [comment]
same problem using mongodb 3.6, seems due to mongo version. But is there someone still maintaining this project?

**Comment by Koronos** [comment]
Same error, I think if @chevex doesn't appear, is necessary create a new project to maintain this plugin. He has not activity since Dec 11, and there are pull request whit the solution. What should we do in this cases?

**Comment by nodkz** [comment]
New maintained package https://github.com/nodkz/mongoose-plugin-autoinc
It fixes this error and bunch of others.

**Comment by nomanbiniqbal** [comment]
+1
