### ISSUE TITLE
Cannot create an index on mydb.identitycounters

### ISSUE THREAD

**Issue by NikitaVlaznev** [chevex-archived/mongoose-auto-increment#78]
What are the options **"required": true** and **"index": -1** in this line?

https://github.com/chevex-archived/mongoose-auto-increment/blob/50bd2a642c7565cf0a9f2c368d437b83160ad0a6/index.js#L21

Mongoose does not have such options and thus fails on creating index:

```
error: Unhandled Rejection at: Promise  Promise {
  <rejected> { MongoError: Cannot create an index on credit.identitycounters with an insert to 5a089281970199410b277a88_credit.system.indexes
    at Function.MongoError.create (/home/aquajet/projects/mfo/api/node_modules/mongodb-core/lib/error.js:31:11)
    at /home/aquajet/projects/mfo/api/node_modules/mongodb/lib/db.js:1094:80
    at /home/aquajet/projects/mfo/api/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'MongoError',
  message: 'Cannot create an index on credit.identitycounters with an insert to 5a089281970199410b277a88_credit.system.indexes',
  index: 0,
  code: 72,
  errmsg: 'Cannot create an index on credit.identitycounters with an insert to 5a089281970199410b277a88_credit.system.indexes' } } MongoError: Cannot create an index on credit.identitycounters with an insert to 5a089281970199410b277a88_credit.system.indexes
```

Here is what i got if i try to create such index in mongo shell:
```
db.identitycounters.ensureIndex({ field: 1, model: 1 }, { unique: true, required: true, index: -1, background: true })
{
	"ok" : 0,
	"errmsg" : "The field 'required' is not valid for an index specification. Specification: { key: { field: 1.0, model: 1.0 }, name: \"field_1_model_1\", unique: true, required: true, index: -1.0, background: true }",
	"code" : 197,
	"codeName" : "InvalidIndexSpecificationOption"
}
```

**Comment by NikitaVlaznev** [comment]
Duplicates: #74 and #77.
