### ISSUE TITLE
Error with mongoose@^5.0.6, it's throwing TypeError: connection.model is not a function

### ISSUE THREAD

**Issue by utkarsh27a** [chevex-archived/mongoose-auto-increment#89]
I am unable to initialize auto increment.

when I start my app it's throwing

```
TypeError: connection.model is not a function
at Object.exports.initialize (/home/vivek/office/modified/the_smbx/node_modules/mongoose-auto-increment/index.js:10:34)
at module.exports (/home/vivek/office/modified/the_smbx/utils/mongo.js:47:19)
at Object. (/home/vivek/office/modified/the_smbx/app.js:12:25)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object. (/home/vivek/office/modified/the_smbx/bin/www:7:11)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Function.Module.runMain (module.js:693:10)
at startup (bootstrap_node.js:188:16)
at bootstrap_node.js:609:3
```

**Comment by rafay1327** [comment]
For mongoose-auto-increment v5.x :
connection = mongoose.**createConnection**('mongodb://<username>:<password>@<database_url>', { useNewUrlParser: true });
autoIncrement.initialize(connection);

var userSchema = new mongoose.Schema({
//define user here
});

userSchema.plugin(autoIncrement.plugin, 'User');
//export user

**Comment by gzwgq222** [comment]
Thanks

**Comment by utkarsh27a** [comment]
> For mongoose-auto-increment v5.x :
> connection = mongoose.**createConnection**('mongodb://:@<database_url>', { useNewUrlParser: true });
> autoIncrement.initialize(connection);
> 
> var userSchema = new mongoose.Schema({
> //define user here
> });
> 
> userSchema.plugin(autoIncrement.plugin, 'User');
> //export user

that error was occurring with `mongoose 5.0.6`, at that time I had done some modifications with the connection mongoose-auto-increment was using in my `node_modules`.
